### ISSUE TITLE
Add Support for Terraform 2.x

### ISSUE THREAD

**Issue by ajay-bangar** [terraform-google-modules/terraform-google-lb#15]
Root directory script has been modified to **Terraform 2.x**, but not the example directory which run into failure due to mismatched version.

**Comment by ajay-bangar** [comment]
Made necessary updates in  #16

**Comment by aaron-lane** [comment]
Hi @ajay-bangar!

This issue is already covered by #14. Updating the syntax of the example is not sufficient as the referenced module is deprecated and does not support Terraform 0.12.
