### ISSUE TITLE
Add support for Terraform 0.13

### ISSUE THREAD

**Issue by bhundven** [terraform-google-modules/terraform-google-lb#30]

**Comment by bhundven** [comment]
also, 0.14 alpha is out...

**Comment by bharathkkb** [comment]
Hi @bhundven 
This module should be compatible with 0.13 (even 0.14-alpha) as we only [require](https://github.com/terraform-google-modules/terraform-google-lb/blob/47c3d0ce33d4841d43c892701c1e55e6b0476521/versions.tf#L18) a version >= 12.0. Did you run into any incompatibilities during its usage with 0.13?

**Comment by bhundven** [comment]
Huh, I tested this a month ago, and got a version error. Tried again with 0.13.1, works fine now. :shrug: 

I'm also looking to make the firewall creation optional. For a project I have, the firewall rules are managed by another deployment. I'll open a issue/PR soon. (same for lb-internal)
