### ISSUE TITLE
No option to select existing instance

### ISSUE THREAD

**Issue by RezaRahmati** [terraform-google-modules/terraform-google-lb#41]
### TL;DR

When adding TCP load balancer in the console, there is an option to select existing instance (of compute engine) as below

![image](https://user-images.githubusercontent.com/10086092/144931122-8d9036b9-1ecc-4ab9-9292-09eb0f8dc6be.png)

The option to add this in the terraform script is missing. 

### Expected behavior

Being able to add instance

### Observed behavior

Parameter is missing

### Terraform Configuration

```hcl
module "lb" {
  source  = "GoogleCloudPlatform/lb/google"
  version = "3.0.0"

  firewall_project = var.firewall_project_id
  project = var.project_id
  name    = var.name
  region  = var.region

  service_port = var.port
  // target_tags  = ["pcm-sftp"]
  network                 = var.network
  target_service_accounts = [var.sa]
}
```

### Terraform Version

```sh
0.14
```

**Comment by morgante** [comment]
This is not a bug. We don't commit to supporting every field in the UI.

You can easily do this by creating an [unmanaged instance group](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/compute_instance_group) and connecting the load balancer to that UMIG.
